# wrangler.toml (Final Correct Version)

# 您的 Worker 名稱
name = "dry-block-0743"

# 主程式檔案
main = "worker.js"

# 相容性日期
compatibility_date = "2025-09-02"

# --- KV 命名空間繫結 ---
# 這是您唯一需要聲明的繫結。
# "binding" 是您在程式碼中使用的變數名。
# "id" 的值將從名為 KV_NAMESPACE_ID 的 GitHub Secret/環境變數中讀取。
[[kv_namespaces]]
binding = "kv" # <--- 請確保這裡的 "MY_KV" 是您程式碼中實際使用的變數名
id = "${KV_NAMESPACE_ID}"

# 就是這樣！您不需要 [secrets] 區塊。
# 只要您的密鑰 (例如 UUID) 已經在 Cloudflare 儀表板上設定好了，
# Wrangler 就會自動保留它，不會將它刪除。
