# wrangler.toml (The Final and Correct Version)

name = "dry-block-0743"
main = "worker.js"
compatibility_date = "2025-09-02"

# [build] 區塊是解決混淆代碼問題的關鍵。
# 我們在這裡提供一個空的 build 指令，
# 這會告訴 Wrangler：「不需要做任何建置或捆綁，
# worker.js 檔案本身就是最終產物，請直接上傳它」。
[build]
command = ""
