# wrangler.toml
name = "dry-block-0743"
main = "worker.js"
compatibility_date = "2025-09-02"

# [vars] 用於存放「非敏感」的公開變數
# 它的值會直接被上傳
[vars]
# API_URL = "https://example.com"

# [secrets] 用於聲明「敏感」的密鑰名稱
# 注意：這裡只寫名字，絕對不要寫值！
# 它的值必須預先在 Cloudflare 儀表板設定好
[secrets]
# SECRET_KEY
