# wrangler.toml (Final Template Version)

name = "dry-block-0743"
main = "worker.js"
compatibility_date = "2025-09-02"

# 確保部署的是原始的混淆代碼
[build]
command = ""

# --- KV 命名空間繫結 ---
# "binding" 是您在程式碼中使用的變數名，即 "kv"
# "id" 是一個獨特的佔位符，我們稍後會用真實 ID 替換它
[[kv_namespaces]]
binding = "kv"
id = "__KV_NAMESPACE_ID_PLACEHOLDER__"
