# .github/workflows/bpb-update.yml (Final Correct Version)

name: Deploy Worker with Full Configuration

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    
    # 我們將 env 區塊從這裡移除，因為它沒有被 wrangler-action 讀取到

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download latest worker.js
        run: |
          LATEST_RELEASE_URL=$(curl -s "https://api.github.com/repos/bia-pain-bache/BPB-Worker-Panel/releases" | jq -r '.[0].assets[] | select(.name == "worker.js") | .browser_download_url')
          curl -L -o worker.js "$LATEST_RELEASE_URL"

      # --- 這是修改過的核心部分 ---
      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          # 直接從 secrets 讀取，更清晰
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
        # 關鍵：將環境變數定義在 step 的內部
        # 這樣可以確保 wrangler-action 在執行時一定能讀取到它
        env:
          KV_NAMESPACE_ID: ${{ secrets.KV_NAMESPACE_ID }}
