name: Deploy BPB Worker to Cloudflare

on:
  # 定時排程：設定為每天 22:00 UTC，即香港時間早上 6:00。
  schedule:
    - cron: '0 22 * * *'
  # 允許您隨時從 GitHub 的 "Actions" 分頁手動觸發此工作流程來立即更新。
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download latest worker.js from BPB-Worker-Panel
        run: |
          # 從 bia-pain-bache/BPB-Worker-Panel 的最新發行版中獲取 worker.js 的下載 URL
          LATEST_RELEASE_URL=$(curl -s "https://api.github.com/repos/bia-pain-bache/BPB-Worker-Panel/releases/latest" | grep "browser_download_url.*worker\.js" | cut -d : -f 2,3 | tr -d \")
          # 下載檔案並命名為 worker.js
          curl -L -o worker.js $LATEST_RELEASE_URL

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          # 已將 Worker 名稱更新為您的 'dry-block-0743'
          name: dry-block-0743
          scriptPath: worker.js
