name: Deploy BPB Worker to Cloudflare

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        # 需要 checkout 才能讓 runner 讀取到您的 wrangler.toml 檔案
        uses: actions/checkout@v4

      - name: Download latest worker.js from BPB-Worker-Panel
        run: |
          LATEST_RELEASE_URL=$(curl -s "https://api.github.com/repos/bia-pain-bache/BPB-Worker-Panel/releases" | jq -r '.[0].assets[] | select(.name == "worker.js") | .browser_download_url')

          if [ -z "$LATEST_RELEASE_URL" ]; then
            echo "::error::Could not find worker.js download URL in the latest release."
            exit 1
          fi
          
          echo "Downloading from $LATEST_RELEASE_URL"
          curl -L -o worker.js "$LATEST_RELEASE_URL"

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          # 指令簡化了！Wrangler 會自動讀取 wrangler.toml 檔案
          command: deploy
