name: Deploy BPB Worker to Cloudflare

on:
  # 定時排程：設定為每天 22:00 UTC，即香港時間早上 6:00。
  schedule:
    - cron: '0 22 * * *'
  # 允許您隨時從 GitHub 的 "Actions" 分頁手動觸發此工作流程來立即更新。
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # --- 這是修改過的部分 ---
      - name: Download latest worker.js from BPB-Worker-Panel
        run: |
          echo "Fetching latest release information..."
          # 使用 jq 工具安全地解析 JSON 並提取 worker.js 的下載 URL
          LATEST_RELEASE_URL=$(curl -s "https://api.github.com/repos/bia-pain-bache/BPB-Worker-Panel/releases/latest" | jq -r '.assets[] | select(.name == "worker.js") | .browser_download_url')

          # 增加一個檢查，確保 URL 真的被找到了
          if [ -z "$LATEST_RELEASE_URL" ]; then
            echo "::error::Could not find worker.js download URL in the latest release."
            exit 1
          fi
          
          echo "Found download URL: $LATEST_RELEASE_URL"
          echo "Downloading worker.js..."
          # 使用獲取到的 URL 下載檔案
          curl -L -o worker.js "$LATEST_RELEASE_URL"
          echo "Download complete."

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          # 部署指令保持不變
          command: deploy --name dry-block-0743 worker.js --compatibility-date 2025-09-02
