# .github/workflows/bpb-update.yml (Final Version with updated workflow name)

# --- 這是修改過的部分 ---
name: Deploy BPB Worker to Cloudflare

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download latest worker.js
        run: |
          LATEST_RELEASE_URL=$(curl -s "https://api.github.com/repos/bia-pain-bache/BPB-Worker-Panel/releases" | jq -r '.[0].assets[] | select(.name == "worker.js") | .browser_download_url')
          curl -L -o worker.js "$LATEST_RELEASE_URL"

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          
          secrets: |
            UUID
            TR_PASS

          kv: |
            kv: ${{ secrets.KV_NAMESPACE_ID }}

        env:
          SECRET_UUID: ${{ secrets.SECRET_FOR_UUID }}
          SECRET_TR_PASS: ${{ secrets.SECRET_FOR_TR_PASS }}
