# .github/workflows/bpb-update.yml

name: Update Cloudflare Worker Script Only

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  deploy-script:
    runs-on: ubuntu-latest
    name: Download and Deploy Script
    steps:
      - name: Download latest worker.js
        run: |
          LATEST_RELEASE_URL=$(curl -s "https://api.github.com/repos/bia-pain-bache/BPB-Worker-Panel/releases" | jq -r '.[0].assets[] | select(.name == "worker.js") | .browser_download_url')
          if [ -z "$LATEST_RELEASE_URL" ]; then
            echo "::error::Could not find worker.js download URL in the latest release."
            exit 1
          fi
          echo "Downloading from $LATEST_RELEASE_URL"
          curl -L -o worker.js "$LATEST_RELEASE_URL"
          if [ ! -s worker.js ]; then
            echo "::error::Downloaded worker.js file is empty."
            exit 1
          fi
          echo "Download complete."

      # --- 這是修改過的核心部分 ---
      - name: Upload Worker Script via Cloudflare API (Multipart format)
        run: |
          echo "Uploading script to Cloudflare Worker: dry-block-0743"
          # 使用 multipart/form-data 格式上傳
          # -F 指定一個表單欄位。我們需要兩個：一個是元數據，一個是腳本檔案本身。
          curl -X PUT "https://api.cloudflare.com/client/v4/accounts/${{ secrets.CF_ACCOUNT_ID }}/workers/scripts/dry-block-0743" \
            -H "Authorization: Bearer ${{ secrets.CF_API_TOKEN }}" \
            -F 'metadata={"main_module": "worker.js"}' \
            -F "script=@worker.js;type=application/javascript+module"
