# .github/workflows/bpb-update.yml (Final Correct Version)

name: Deploy Worker with Full Configuration

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    
    # 關鍵：將 GitHub Secrets 映射為環境變數
    env:
      CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      KV_NAMESPACE_ID: ${{ secrets.KV_NAMESPACE_ID }}
      # 如果您有其他 secrets，也像這樣加在這裡
      # A_SECRET_KEY: ${{ secrets.A_SECRET_KEY }}

    steps:
      # 步驟一：Checkout 程式碼，這樣才能讀取到 wrangler.toml
      - name: Checkout repository
        uses: actions/checkout@v4

      # 步驟二：下載最新的 worker.js
      - name: Download latest worker.js
        run: |
          LATEST_RELEASE_URL=$(curl -s "https://api.github.com/repos/bia-pain-bache/BPB-Worker-Panel/releases" | jq -r '.[0].assets[] | select(.name == "worker.js") | .browser_download_url')
          curl -L -o worker.js "$LATEST_RELEASE_URL"

      # 步驟三：使用 Wrangler 進行部署
      # Wrangler 會自動讀取 wrangler.toml 和所有環境變數，進行一次完整的、安全的部署
      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          # apiToken 和 accountId 現在從 env 中傳遞，更加清晰
          apiToken: ${{ env.CF_API_TOKEN }}
          accountId: ${{ env.CF_ACCOUNT_ID }}
