# .github/workflows/bpb-update.yml (The Absolutely Final Version with Version Lock)

name: Deploy BPB Worker to Cloudflare

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download latest worker.js
        run: |
          LATEST_RELEASE_URL=$(curl -s "https://api.github.com/repos/bia-pain-bache/BPB-Worker-Panel/releases" | jq -r '.[0].assets[] | select(.name == "worker.js") | .browser_download_url')
          curl -L -o worker.js "$LATEST_RELEASE_URL"

      - name: Substitute KV ID in wrangler.toml
        run: |
          sed -i "s/__KV_NAMESPACE_ID_PLACEHOLDER__/${{ secrets.KV_NAMESPACE_ID }}/g" wrangler.toml
          echo "--- Patched wrangler.toml ---"
          cat wrangler.toml

      - name: Upload Secrets to Cloudflare
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          echo "Uploading secrets..."
          # 安裝並使用一個穩定的 Wrangler v3 版本來上傳祕密
          npm install --save-dev wrangler@3.57.0
          echo "${{ secrets.SECRET_FOR_UUID }}" | npx wrangler@3 secret put UUID
          echo "${{ secrets.SECRET_FOR_TR_PASS }}" | npx wrangler@3 secret put TR_PASS
          echo "Secrets uploaded."

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          # --- 這是新增的、最關鍵的一行 ---
          # 鎖定 wrangler 的版本，確保我們的工作環境穩定且可預測
          wranglerVersion: '3.57.0'
