name: Deploy to OCI

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      OCI_CLI_USER: ${{ secrets.USER_OCID }}
      OCI_CLI_TENANCY: ${{ secrets.TENANCY_OCID }}
      OCI_CLI_FINGERPRINT: ${{ secrets.FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.PRIVATE_KEY }}  # 改為 KEY_CONTENT
      OCI_CLI_REGION: ${{ vars.REGION }}
    steps:
    - uses: actions/checkout@v3

    - name: Get Image OCID
      uses: oracle-actions/run-oci-cli-command@v1.3.2
      id: get-image
      with:
        command: 'compute image list --compartment-id ${{ secrets.COMPARTMENT_ID }} --operating-system "Canonical Ubuntu" --operating-system-version "24.04" --shape "VM.Standard.A1.Flex"'
        query: "data[? \"display-name\" == 'Canonical-Ubuntu-24.04-aarch64-2025.07.23-0'].id | [0]"

    - name: Check Image ID
      run: |
        if [ -z "${{ steps.get-image.outputs.raw_output }}" ]; then
          echo "Error: Image not found for build 2025.07.23-0"
          exit 1
        fi

    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0  # 調整為最新

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: |
        terraform plan \
          -var "tenancy_ocid=${{ secrets.TENANCY_OCID }}" \
          -var "user_ocid=${{ secrets.USER_OCID }}" \
          -var "fingerprint=${{ secrets.FINGERPRINT }}" \
          -var "private_key=${{ secrets.PRIVATE_KEY }}" \  # 改為 private_key
          -var "region=${{ vars.REGION }}" \
          -var "compartment_id=${{ secrets.COMPARTMENT_ID }}" \
          -var "subnet_id=${{ secrets.SUBNET_ID }}" \
          -var "image_id=${{ steps.get-image.outputs.raw_output }}" \
          -var "ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}"  # 可選

    - name: Terraform Apply
      run: |
        terraform apply -auto-approve \
          -var "tenancy_ocid=${{ secrets.TENANCY_OCID }}" \
          -var "user_ocid=${{ secrets.USER_OCID }}" \
          -var "fingerprint=${{ secrets.FINGERPRINT }}" \
          -var "private_key=${{ secrets.PRIVATE_KEY }}" \  # 改為 private_key
          -var "region=${{ vars.REGION }}" \
          -var "compartment_id=${{ secrets.COMPARTMENT_ID }}" \
          -var "subnet_id=${{ secrets.SUBNET_ID }}" \
          -var "image_id=${{ steps.get-image.outputs.raw_output }}" \
          -var "ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}"

    - name: Output Results
      run: |
        echo "Instance Public IP: $(terraform output -raw instance_public_ip)"
        echo "SSH Password: $(terraform output -raw ssh_password)"  # 這會在 log 中顯示密碼，請小心
